### ISSUE TITLE
Facebook group admin/moderator issue when trying to open from notifcations

### ISSUE THREAD

**Issue by ThirdEyeClarity** [AllanWang/Frost-for-Facebook#1216]
Not sure if this is related to issue #1176  but basically when I try to moderate (pending posts or adding members) from the notifications, it doesn't load up, just a bunch of code.  Works fine if you manually go to the group page to moderate however so it's not a big deal. See [my screen recording](https://streamable.com/anbhx) where I reproduce this.
(v2.1.2)

**Comment by AllanWang** [comment]
You're right. I'm aware of the problem, though I haven't gotten around fixing it.

When I created the first issue, Facebook basically switched the page so that it became "dependent" on the page before it. Even if you go on m.facebook.com on your browser and try refreshing, the same error occurs. I'm not sure why the first page is blank, though I'm guessing it's because I'm filtering out some tracking ids which it now needs. I will definitely get a solution by the end of winter break, given I'm a mod in a lot of groups, though it would probably have to be removing any filtering when a link is for pending members.

They're doing this more and more, so I'm not impressed at all. The menu page is a good example of this, as you can only access it if you load something else first.

**Comment by ThirdEyeClarity** [comment]
It seems to suddenly be working now.

**Comment by AllanWang** [comment]
Guess they changed it back. You can refresh too which is good, so I'll have to revert my previous change in the future.
