### ISSUE TITLE
Check 'leave group' action

### ISSUE THREAD

**Issue by AllanWang** [AllanWang/Frost-for-Facebook#1229]
Reported that it may not work

**Comment by palafix** [comment]
It's not only in group, also in friends section, the buttons in facebook page not responding when click on it.
This is because of the User Agent (Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36).

Change it to (Mozilla/5.0 (Linux; Android 7.1; Mi A1 Build/N2G47H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36) with this User Agent MESSENGER will not work so you need to give the MESSENGER url a different User Agent to work like this User Agent (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36). 
Hope it will help.

**Comment by palafix** [comment]
It's on the repo i use  and test, here it is. It's not that clean, but i'm learning ;). 
 [](https://github.com/palafix/Flash)
