### ISSUE TITLE
Fix login

### ISSUE THREAD

**Issue by AllanWang** [AllanWang/Frost-for-Facebook#1256]
For some reason, setting cookies doesn't end up matching the one supplied. It looks like new fields are being added automatically?

**Comment by mdaniel** [comment]
The weird thing is that it appears the app is in a semi-authenticated state, because it still emits activity notifications for my account, and some navigation actions within the app work

And I suspect you already know, but for clarity once this bug strikes, even trying to login no longer works; it redisplays the login screen on submission
