### ISSUE TITLE
Option to save password on One tap log in & Autoplay video

### ISSUE THREAD

**Issue by zputnyq** [AllanWang/Frost-for-Facebook#1339]
Hi Allan Wang.
I like your app, it's great

Probably it should be feature request.
The interval between welcome screen & saving password for one tap log in is somehow too fast after using frost for a few times. I think it should be longer so saving password for one tap log in could be rejected. Morever, it would be great if there is a feature to turn off video autoplay.
I'm using xperia m4 stock 6.0.1 with nautilus kernel.
Thank you, I really appreciate it

Best regards,

**Comment by AllanWang** [comment]
The transition from logging in to opening the app is as fast as possible because one tap doesn't apply here. You aren't really meant to log out of Frost for general use, and logging out results in the expectation that you want to enter a password again to log in. If you want to add multiple accounts, you can do directly without logging out either.

You can disable auto play through facebook settings by going to https://touch.facebook.com/settings/videos/ on your device.
