### ISSUE TITLE
Swipe to go back for image view

### ISSUE THREAD

**Issue by ltGuillaume** [AllanWang/Frost-for-Facebook#1351]
It would be nice to be able to return from the image view (long press an image) with the swipe right gesture, be it _only from the left edge_ when zoomed. This way, it's not in the way of scrolling when zoomed in, but can still be used to return to the previous page.

**Comment by AllanWang** [comment]
I may think about this (I'd prefer vertical swipes), but this is really low priority as there are other bugs and fixes I need to work on.

**Comment by ltGuillaume** [comment]
Vertical swipes? I wouldn't really understand that: how would users be visually cued to swipe vertically, while they already know that swiping right does the same thing elsewhere?

**Comment by AllanWang** [comment]
Swipe right works in most cases because panels are actually animated as coming from the right edge. However, that does not occur in the image activity. If you look at most gallery apps, they do in fact support vertical swipes to exist, whereas horizontal swipes are typically reserved for switching photos in an album (which may exist eventually in Frost).

Relay for Reddit is also a good example of a UI that's heavily based on swipes, and has a vertical image swipe gesture

**Comment by ltGuillaume** [comment]
Switching images in albums, of course, didn't think of that.

**Comment by AllanWang** [comment]
You can try this

https://github.com/AllanWang/Frost-for-Facebook-APK-Builder/releases/tag/v2414
