### ISSUE TITLE
white font on light background in dark theme

### ISSUE THREAD

**Issue by bennypr0fane** [AllanWang/Frost-for-Facebook#1392]
In dark theme, When type-to-searching for contacts in message composer screen, matching contacts' names are displayed in white font on very light background, hardly legible
![sketch-1554743824873](https://user-images.githubusercontent.com/5002396/55744537-78ebda00-5a35-11e9-87a1-767cd5a13b0f.png)

**Comment by AllanWang** [comment]
Which Frost version?

**Comment by bennypr0fane** [comment]
2.2.3, I installed it today from F-Droid

**Comment by Clickau** [comment]
This still happens on 2.2.4 on dark or amoled theme on the Groups page and sometimes on the page with the questions you have to answer to enter a group.

**Comment by AllanWang** [comment]
Can you elaborate on where on the group pages? I'd have to find a group with questions to fix that one

**Comment by Clickau** [comment]
![Capture+_2019-04-30-19-48-45](https://user-images.githubusercontent.com/40263542/56978978-66bb1280-6b81-11e9-9950-14db104fd674.png)
I was talking about this page. When i posted this, i tried switching back and forth between normal and amoled/dark theme and the issue persisted (on the black themes, the background and also the text were black on this page), but now, when i changed the theme back to amoled, it displays normally, with white text. So idk, if the issue comes back, i'll update

**Comment by AllanWang** [comment]
Looked myself and currently don't see any parts unthemed. If a problem occurs, file another issue. Thanks
