### ISSUE TITLE
[enhancement] The maximum number of main activity tabs determined by DPI/resolution

### ISSUE THREAD

**Issue by MegaAhmadF** [AllanWang/Frost-for-Facebook#1426]
Very low priority I guess.

Make main activity tabs up to a specific number, preferably determined by display properties, meaning one could set it to less than 4 tabs when needed, or more than 4 if screen allows it.
Or even just remove the limit allowing users to select whatever number of tabs they want.

**Comment by AllanWang** [comment]
Sorry for the late reply.

There isn’t really anything stopping such configuration beyond a hardcoded constant. With that said, I would still enforce 4 tabs as a max since all tabs are preloaded at once. While your ui may fit more, it would be wasteful to have many more tabs preloaded, especially since most of them will constantly ping facebook for various information.

Note that you can customize which tabs you want through settings. Most main entry points are also available in the nav drawer, where they aren’t preloaded.
