### ISSUE TITLE
Reaction text colour isn't changing.

### ISSUE THREAD

**Issue by abhishekabhi789** [AllanWang/Frost-for-Facebook#1497]
After reacting to a comment with like, haha, sad, angry etc. usually the text colour changes with respect to the reaction applied.
 Here with frost app, the the reaction actually loads successfully but the text isn't changing.(Like)  so can't understand whether the reaction applied or not.
Tested with Light and AMOLED theme. 

**Expected result:** 
If added reaction is 'Love' then the 'Like' text should changes to 'Love' in red colour.

**Steps to reproduce the behaviour:**
1. Open any Facebook post
2. Click on  'Like' under any comment (or long press to add any reaction)
3. The number of reactions increased can be noticed, meanwhile the 'Like' text remain unchanged.
Frequency of bug: Every time.

**Details**
 - App Version: 2.3.1
- App source : F-Droid
 - Device: Xiaomi Redmi Note 4 (SD) Havoc Os 2.7
 - Android Version: 9.0

**Comment by AllanWang** [comment]
There isn't really a good way to keep the custom text colors, since it is dependent on the theme. For instance, if someone uses a custom theme with yellow text, they won't be able to see the difference. I have instead added some css changes so that (any) action will become an accent color. You can always see the text change for the respective reaction

**Comment by SakiiCode** [comment]
The accent color doesn't work with comments, only in default theme.
