### ISSUE TITLE
Block read receipt/seen status for messages

### ISSUE THREAD

**Issue by mavaa** [AllanWang/Frost-for-Facebook#1526]
**Describe the feature**
On my desktop I use a plugin for Firefox called "Unseen for Facebook": https://addons.mozilla.org/en-US/firefox/addon/chat-facebook-unseen/

It will prevent messages I read from being marked as such, so than others don't get the " seen" status in their messages. I think the only thing the plugin does is block requests to one or more URLs, but I'm not sure if this would work the same way on mobile. Would this be possible as a setting or something like it?

**Comment by AllanWang** [comment]
It's possible and I've done it before unintentionally, but there are other problems like message syncing. I don't plan on pushing a feature like that where users would expect it to be reliable. It'll break too easily, and there's also no way for me to push updates quickly in the event that happens.

If there are other open source extensions, you can let me know, but I've looked up some others that just hide the seen icon rather than blocking any requests

**Comment by mavaa** [comment]
That's perfectly understandable, thanks for responding! :slightly_smiling_face:
