### ISSUE TITLE
The navigation is strange

### ISSUE THREAD

**Issue by azat11** [AllanWang/Frost-for-Facebook#1527]
When I'm opening a profile, for example, and start looking through photos there, I can not go back to the profile. It always throws me back to my profile and I have to start from the beginning. This is no matter how I do it, swipe right, press back, or press the cross in the corner.
How do I navigate back without closing everything?

**Comment by azat11** [comment]
Well, I'm switching back to SlimSocial, the Frost has become unusable because of this.

**Comment by AllanWang** [comment]
You are free to use whichever app you'd like, but that doesn't really help the bug report.

As for reproducibility, Facebook has their own weird backstack. In most cases, I cannot replicate what you said with pressing back. Some instances will go back to the newsfeed if you go back from photos, but pressing back again will go to the profile. You can start by letting me know if SlimSocial has the same problem.

Swiping and clicking exit were always meant to close the whole panel, so that is expected.

**Comment by azat11** [comment]
In SlimSocial pressing back more often does exactly that. As an example I noticed, only if I was redirected from a search of groups by pressing join, it seems to forget where I was and returns me to the feed when I press back from that.

Granted, I didn't pay much attention to the sequnce of this in the Frost, but it happened much more often.

I'll try using it again and will report back with what I see.

**Comment by azat11** [comment]
So, here's one. When going through photos, when pressing back it goes to the feed, only then to previous photo, to the feed, to the photo, and so on.
SlimSocial doesn't do this.

Also noticed SlimSocial loads a lot faster. There's a few seconds before each next photo loads in Frost.

**Comment by AllanWang** [comment]
That's a Facebook web issue, and you'll probably be able to replicate it in any browser. I will be working on reducing the number of web overlays, since there are still two from back when two user agents are supported. That won't affect your current problem though.

**Comment by AllanWang** [comment]
Related change from before: #1177
