### ISSUE TITLE
Notifications Tab Items Don't Change

### ISSUE THREAD

**Issue by GiantWaffle** [AllanWang/Frost-for-Facebook#1547]
Hi,

LG V20 (H910)
Nougat 7.0

This started with (GitHub) v2.4.0

I'm not sure what the Tab is called.  I think it's the "Notifications Tab".  It's the Tab that shows, for example, "Bob liked your comment", or, "Joe has replied to your comment", etc..

Anyway, it lists them (Notifications?) and the ones that you have not tapped on are grey and the ones that you have tapped on turn white.  This is obviously so you know what you've looked at and what you haven't.

But besides how they now look listed out (which looks fine), what is happening now, is that after viewing them, they do not always turn white and so some of the ones that you have looked at already appear as if you haven't.

It is not every time, but does happen often.  I did try exiting and running the app again, but the ones that didn't change remain unchanged.

-

**Comment by AllanWang** [comment]
It seems like you have to refresh for the changes to apply. In most instances, navigation happens on one page, and so you must press back to go to the list, which probably refreshes it. In the future I will add a context item so you can go to the list again in the overlay, which loads faster anyways. Previously, I used native ui elements and had my own post request to mark notifications as read, but since they were a potential cause of phishing warnings, I've removed that feature in #1542.

I will look into it to see if I'm somehow blocking the change

**Comment by GiantWaffle** [comment]
Allan,

I did try all of that.  Refreshing was the first thing I tried.  Also switching Tabs, Refreshing again, Back button, exiting Frost, then running it again, Refreshing it again, Rebooting my phone, then running Frost again, Refreshing again, etc., etc.. :-)

But whichever Tabs didn't turn white, still wouldn't turn white.

**Comment by AllanWang** [comment]
Can you confirm that the layout looks different? As of 2.4.0, you should be seeing the same layout as the website, as native ui is disabled. If refreshing doesn't work, I feel like you are actually using an older version. Test builds and release builds can be installed alongside each other. Let me know if you can confirm it's for 2.4.0

**Comment by GiantWaffle** [comment]
No, it's v2.4.0 for sure and it's the only Frost on this device.  I even just double checked.

I understand there were issues that you needed to resolve and changed the User Agent, but I do wish there were a way to have just the Notifications Tab the way it was.
