### ISSUE TITLE
own conversation output is invisible if accents and fonts are set as black [frost-test]

### ISSUE THREAD

**Issue by alekksander** [AllanWang/Frost-for-Facebook#1566]
![blck9](https://

**Comment by AllanWang** [comment]
As you probably figured out, accent colors should be visible against both the text and background colors.

**Comment by alekksander** [comment]
sorry for creating noise. there still isn't a proper way to combine my „black on white” understanding of app visual aspect, but i don't want to create any more hassle about it and will simply get use to inconveniences, or use another color. to do it „my way” is probably to create another custom template like „black on white”, or add more customized elements. by the way, i still have some trouble to understand what are accents (seems to be own conversation output + pages/people's name at wall), why icon text changes text color and so on… it's just unclear to me personally.

**Comment by AllanWang** [comment]
Accents are more like highlights. For instance, in most cases, people want links to be different colors, since they would otherwise be indistinguishable. In some cases I may also use accents as a background, if for some reason there are foreground colors that must be the background color.

For you, a grey accent may meet your needs. It's impossible to accommodate everyone, since some people may want two colors, whereas others may want to customize everything differently.

**Comment by alekksander** [comment]
Yes, so wouldn't it be most reasonable to add more colors to customize? seperate color for links, perhaps different template for conversations, or just an option to select own/interlocutor chat bubbles?  i think also badges on icons (count number for new content) should also have different coloring. I think it's possible with css and i don't see why not to introduce it, however i'd love some further explanation why it's not such a good idea as well :) thanks!

**Comment by AllanWang** [comment]
It becomes a pain to maintain. The [css classes](https://github.com/AllanWang/Frost-for-Facebook/tree/dev/app/src/web/scss/core) are not descriptive, so even if you do label it correctly for one area, there is no guarantee it isn't used for another style elsewhere.
