### ISSUE TITLE
Facebook account locked

### ISSUE THREAD

**Issue by AllanWang** [AllanWang/Frost-for-Facebook#1694]
I'm having this issue too. Facebook locked my account twice in a week. I'm quite certain I wasn't phished. I haven't even used Facebook outside of Frost.

_Originally posted by @evanbishop in https://github.com/AllanWang/Frost-for-Facebook/issues/1675#issuecomment-655691669_

**Comment by MrMightyNighty** [comment]
Same here. My account got locked. No phising happened. 2FA is activated.

**Comment by AllanWang** [comment]
Did your account just get locked or was there also a message associated with it? With the previous problem, it said the lock was due to suspected phishing. Do you also regularly post/comment, or is this a problem with just reading content through frost?

**Comment by evanbishop** [comment]
For what it's worth, in my case Facebook made it clear it was suspected phishing. I do not regularly post or comment but I do use Frost to send messages on a regular basis.

**Comment by AllanWang** [comment]
Ok I'll monitor messages (I mostly just read content). I don't really have any ideas on what I could do to address the problem if it exists, beyond maybe going forth with messenger support and hoping it's not a problem there.

Can you also confirm your app version just to make sure it isn't outdated?

**Comment by evanbishop** [comment]
I'm on version 2.4.5

**Comment by MrMightyNighty** [comment]
Sorry for the pretty poor response from my side. Yes, it was also due to suspected phishing. I comment or post pretty rarely (probably like once or twice every two months). I even use Facebooks "Messenger Lite" since I have to send my parents their plane tickets from time to time and this isn't possible with Frost. 

I usually just read through content. Version is 2.4.5.

EDIT: AFAIK I wasn't phished, thats why I wrote in my first post "No phishing happened" but the reason according to Facebook was phishing.

**Comment by GibberMeJenks** [comment]
@AllanWang Hi Allan and everyone. 

I was here when this problem last occurred - for me the previous problem was because I regularly logged in on FB through my desktop and ignored the Frost warning that an unknown device logged in and to confirm that it was myself who accessed my account. I will share what I have been doing in my case to prevent this issue but it may not be applicable to everyone.

Since the last Frost update that was issued a while ago to fix the previous account locking issue, right now I have not had a problem with my account being locked by doing the following regularly every time I login on desktop and not Frost on my phone:

1. Login in to Facebook for desktop whenever you need to or want to
2. Go to Frost - you will see a notification saying there was a sign-in on an unauthorized or unknown device
3. Verify this was you and confirm you were logging in
4. Select forget browser

It is a bit of a pain, but for me no problems so far. Will update if I get the locked warning as well!

**Comment by evanbishop** [comment]
I have not seen the "unknown device" warning like @GibberMeJenks mentioned but if I do I will try that out.

I was locked out of my Facebook account again this week. This time they demanded photo ID to unlock it, which I wasn't willing to give them. (the other option was to identify which 4 comments I had written recently, but I'm 100% positive they only gave me three that I had written...) Eventually they let me through with just a password change, for some reason.

**Comment by idodoron11** [comment]
I don't know if it is related, but I got an email from Facebook, saying 

> "we notices you're having trouble logging into your account. [...] click the button below and we'll log you in".

This messages was received at 4:12 AM, and I'm pretty sure I was sleeping at the time, so it wasn't me. A few minutes later another message was sent, with a password reset link. Again - it wasn't me. Can it be that someone has planted malicious code somewhere in the app that actively gathers users' login information?

**Comment by AllanWang** [comment]
@GibberMeJenks is the unknown device screen persistent, or does Frost automatically move away from it when you log in? It would be difficult for me to support any special handling since I can't typically see the page, but if Frost is animating away and I get the html contents I can look into it.

All I can say now is to use Frost with caution. It is naturally not my intent for users to be banned, and I have not currently faced the problem (though I pretty much never comment or message within Frost).

**Comment by GibberMeJenks** [comment]
@AllanWang sorry for the delay in my reply. 

Basically what happens when I login from my desktop, Frost gives me a notification that an unknown device has signed in. I click on the notification in Frost, select that the login was in fact from me (after confirming that it was 100% me logging in), and choose not to remember the browser.

I do this whenever I login from my desktop. There was a time when I missed several notices from Frost and never bothered to respond where I was then locked out.

Since doing the above and verifying the login from my desktop in Frost, I have not been logged out or had my account locked.

**Comment by AllanWang** [comment]
No actionable items here. If your account is locked, read the comments above and start a new issue if it happens multiple times
