### ISSUE TITLE
Build fails on dev branch right after git clone

### ISSUE THREAD

**Issue by hydrocat** [AllanWang/Frost-for-Facebook#1705]
**Describe the bug**
Hi, I just want to point out that Android Studio complains with the following message and aborts compilation:
> This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.1 or newer.

However, switching to _master_ branch did fix the issue.  Perhaps it is something minor.

Note that the plain git clone checked out the _dev_ branch, that is, by default, _origin/HEAD_ pointed to _origin/dev_

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone Repository
2. (In Android Studio) File -> Sync Project with Gradle Files
3. ???
4. Error

**Details (please provide at least the app version):**
 - App Version: Latest
 - InteliJ Version: 4.0.1
 - Android SDK Version: 10.0 (Android Q)

_Feel free to dismiss this issue if it is irrelevant_

**Comment by AllanWang** [comment]
Your Android Studio build is outdated. Master is working because it barely gets updated.
It used to be for automated play store releases, but that is no longer a thing.

I work with the newest AS betas. You can also check the version I'm on based on the android gradle version

https://github.com/AllanWang/KAU/blob/dev/buildSrc/src/main/kotlin/kau/Versions.kt#L89
