### ISSUE TITLE
Removing tracking label in F-Droid

### ISSUE THREAD

**Issue by AllanWang** [AllanWang/Frost-for-Facebook#1738]
Thanks, @IzzySoft ! I understand that I should open the issue or MR in the F-Droid GitLab.

I don't have a GitLab account, though, and I'm a bit reluctant to create one just for this issue. I'm also not familiar with F-Droid's contribution processes and the four pages of subprojects are a bit overwhelming.

Therefore, I'll post the references here for now. Would it be OK for you to copy them to the proper place in the F-Droid GitLab? I'm posting the raw Markdown at the bottom for easy transfer.

---
In the latest version (2.4.7) of Frost, the tracking library Bugsnag is not used. The relevant code fragments have been commented out:
* [Initialisation in `FrostApp.kt`](https://github.com/AllanWang/Frost-for-Facebook/blob/v2.4.7/app/src/main/kotlin/com/pitchedapps/frost/FrostApp.kt#L74)
* Configuration upon analytics preference change in [`CorePrefs.kt`](https://github.com/AllanWang/Frost-for-Facebook/blob/v2.4.7/app/src/main/kotlin/com/pitchedapps/frost/prefs/sections/CorePrefs.kt#L97-L105) and [`OldPrefs.kt`](https://github.com/AllanWang/Frost-for-Facebook/blob/v2.4.7/app/src/main/kotlin/com/pitchedapps/frost/prefs/OldPrefs.kt#L115-L123)
* [Logging configuration in `L.kt`](https://github.com/AllanWang/Frost-for-Facebook/blob/v2.4.7/app/src/main/kotlin/com/pitchedapps/frost/utils/L.kt#L65-L70)

These changes were introduced with [commit `9d0feeed`](https://github.com/AllanWang/Frost-for-Facebook/commit/9d0feeed6a6aa4e88a115e06778f215faaefc3a8) that is first contained in version 2.4.6.

So 2.4.5 was the version where Bugsnag was still used.

---
```markdown
In the latest version (2.4.7) of Frost, the tracking library Bugsnag is not used. The relevant code fragments have been commented out:
* [Initialisation in `FrostApp.kt`](https://github.com/AllanWang/Frost-for-Facebook/blob/v2.4.7/app/src/main/kotlin/com/pitchedapps/frost/FrostApp.kt#L74)
* Configuration upon analytics preference change in [`CorePrefs.kt`](https://github.com/AllanWang/Frost-for-Facebook/blob/v2.4.7/app/src/main/kotlin/com/pitchedapps/frost/prefs/sections/CorePrefs.kt#L97-L105) and [`OldPrefs.kt`](https://github.com/AllanWang/Frost-for-Facebook/blob/v2.4.7/app/src/main/kotlin/com/pitchedapps/frost/prefs/OldPrefs.kt#L115-L123)
* [Logging configuration in `L.kt`](https://github.com/AllanWang/Frost-for-Facebook/blob/v2.4.7/app/src/main/kotlin/com/pitchedapps/frost/utils/L.kt#L65-L70)

These changes were introduced with [commit `9d0feeed`](https://github.com/AllanWang/Frost-for-Facebook/commit/9d0feeed6a6aa4e88a115e06778f215faaefc3a8) that is first contained in version 2.4.6.

So 2.4.5 was the version where Bugsnag was still used.
```

_Originally posted by @mbeko in https://github.com/AllanWang/Frost-for-Facebook/issues/1491#issuecomment-757041015_

**Comment by AllanWang** [comment]
I will try to send a request for it this weekend. Thanks for digging up the relevant links

**Comment by mbeko** [comment]
Thanks a lot for taking this over!

And sorry for having hijacked that closed issue, I haven't thought about opening a new one.

**Comment by IzzySoft** [comment]
Checking the latest APK from F-Droid (2.4.7), my library scanner still reports:

```
Libraries detected:
-------------------
* Android Support v4 (/android/support/v4): Development Framework
* AppCompat (/androidx/appcompat): Utility
* Biometric (/androidx/biometric): Utility
* Constraint Layout Library (/androidx/constraintlayout): Utility
* Androidx Core (/androidx/core): Utility
* Lifecycle (/androidx/lifecycle): Utility
* Media (/androidx/media): Utility
* Room (/androidx/room): Utility
* Material Dialogs (/com/afollestad/materialdialogs): UI Component
* ViewPager Dots (/com/afollestad/viewpagerdots): UI Component
* Bugsnag exception reporter for Android (/com/bugsnag): Utility Tracking
* Glide (/com/bumptech/glide): Utility
* Subsampling Scale Image View (/com/davemorrissey/labs/subscaleview): UI Component
* ExoMedia (/com/devbrackets/android/exomedia): Utility
* Google Material Design (/com/google/android/material): Utility
* AboutLibraries (/com/mikepenz/aboutlibraries): Utility
* FastAdapter (/com/mikepenz/fastadapter): Utility
* Android-Iconics (/com/mikepenz/iconics): Utility
* kotlinx.coroutines (/kotlinx/coroutines): Utility
* jsoup (/org/jsoup): Utility

Offending libs:
---------------
* Bugsnag exception reporter for Android (/com/bugsnag): Tracking
```

So Bugsnag unfortunately is still there. Looks like some place was missed. Maybe instead of just commenting it out, removing it completely? Your `build.gradle` [still has](https://github.com/AllanWang/Frost-for-Facebook/blob/v2.4.7/app/build.gradle#L2)

```gradle
apply plugin: 'com.bugsnag.android.gradle'
```

Commenting out that one should bring up the remaining places (triggering the corresponding exceptions).

**Comment by AllanWang** [comment]
From https://f-droid.org/en/docs/Anti-Features/#Tracking 
```
Examples of where it would not be applied - any of the above, if the functionality is opt-in (i.e. you are asked before it happens) or disabled by default.
```

Bugsnag is intended to be added at all times, but it was made opt in. So it seems like it fits the status of not having the tracking label.

**Comment by IzzySoft** [comment]
Thanks @AllanWang – that fits: if it's opt-in, the `Tracking` Anti-Feature should not be required (reference: FairEmail uses a similar setup with Bugsnag and doesn't have the `Tracking` Anti-Feature at F-Droid).

I'm not using *any* of Facebook's services (and do not intend to, especially for their, oops, tracking their users and non-users as well), so I cannot verify. But in this process, several users seem to have confirmed already, so I take your (and their) word for it – plus the code links you gave. Find the related [MR here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8094), removing the `Tracking` Anti-Feature with the next index update.

**Comment by mbeko** [comment]
Thanks for the quick handling of my question. Just a word of clarification based on my detailed browsing of the code yesterday.

I think that Bugsnag shows up in the library scanner because of that `apply` and other such lines in the build files. It means that the [Bugsnag Gradle plugin](https://github.com/bugsnag/bugsnag-android-gradle-plugin) is used at _build time_. Also, the Bugsnag library is declared as a dependency of Frost, so it could potentially be used in the code, i.e. at _run time_, but with the current state of things, it isn't. It's not even opt-in because Bugsnag isn't initialised.

So to reassure you: I have searched for "bugsnag" (case-insensitive) in the repository and all the occurrences in the code are commented out.

As a side note for @AllanWang: The `apply` has been actually commented out in the commit that disabled Bugsnag usage, but it has been included again in commit [`eefffafcf`](https://github.com/AllanWang/Frost-for-Facebook/commit/eefffafcf962c0126a0bb3ee5f166412c725072d).

If you intend to remove Bugsnag altogether also from the build and configuration files to avoid confusion if that library is used, here are the remaining spots besides the commented out code that I found:
* [extra property](https://github.com/AllanWang/Frost-for-Facebook/blob/v2.4.7/app/build.gradle#L138)
* [project dependency](https://github.com/AllanWang/Frost-for-Facebook/blob/v2.4.7/app/build.gradle#L301)
* [build script dependency](https://github.com/AllanWang/Frost-for-Facebook/blob/v2.4.7/build.gradle#L12)
* [badge in readme fiile](https://raw.githubusercontent.com/AllanWang/Frost-for-Facebook/v2.4.7/README.md) (line 7)

**Comment by IzzySoft** [comment]
> Bugsnag shows up in the library scanner because

… the library is included with the APK. That doesn't tell whether it's used at all, correct – it just tells the code is there. This analysis (called "static analysis") is based on decompiling the APK and looking at the Smali code. Check [Apktool](https://github.com/iBotPeaches/Apktool) for details, that's what is used under the hood. A lot of analyzers do it that way, so feeding your F-Droid APK to Exodus [shows the same result](https://reports.exodus-privacy.eu.org/en/reports/160023/) for example.

That's why I recommended if you don't use it, better remove it altogether – as users will come with those reports and demand the `Tracking` flag be added back. And try telling them "it's there but it's not used", that will just bring up the very same argument: if you don't use it, then why is it included? As long as the app's decription clearly states its presence, states its opt-in nature and says where to check, it should be fine and you could answer "RTFM" :wink:

> So to reassure you

Thanks! If I had doubts left, I had not already acted and removed the AntiFeature :wink:

**Comment by mbeko** [comment]
I see, I thought the scanner works on source code level. So that fits – as the library is declared as a dependency in the build files, it's included in the APK.

I agree about the complete removal. I would even remove the commented out code as it's in the Git history if needed later. Let's see if AllanWang is fine with that. If so, they should be able to use my references to remove everything without much effort.

**Comment by IzzySoft** [comment]
> I thought the scanner works on source code level.

Exodus can't do that as it doesn't know where the source is. Neither can Apktool if you hand it only the APK. As ***my*** repo is a "simple binary repo", the tools ***I*** use match that.

F-Droid of course also has source code scanning, but then again mostly works at the `build.gradle` to see what's declared (though not only). Understand that a full flavored source code analysis would be quite complex. Suggestions are welcome if there's something completely FLOSS which could be integrated in the work flow – but for this I have to refer you to the team handling the server software :wink:

**Comment by AllanWang** [comment]
Thanks for updating. Change made by Izzy at https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8094

As for Bugsnag, it's meant to be there to facilitate bug reports, though to be honest, I don't really look at them at all. I'm open to removing it if there are other ways for people to easily capture reports. People can choose to get a logcat themselves, but even with all of us on GitHub, I wonder if the general population will do it. With that said, new bugs are often with the website changes, rather than actual crashes.

Since I'm also in more of a maintenance phase, maybe I won't care as much with bug fixing until users create an issue and generate reports.

**Comment by AllanWang** [comment]
Actually you're right. I disabled Bugsnag at one point because it wasn't compatible with the newest Android Studio. I'm sure it's fixed now, but since I don't look at reports anyways and it matters to users, I will probably remove it.

I take it that if an issue is important enough, people will report it here alongside their own bug report.

**Comment by IzzySoft** [comment]
@AllanWang AFAIK ACRA has a nice option to "email bug reports/crashes". It automatically opens a dialog showing what is to be sent, and leaves it to the user to hit "send" or "cancel" (to put into easy terms). I'm collecting some alternatives [here](https://gitlab.com/snippets/1896503#acceptable-analytics) – so you might wish to look and take a pick or, if you know other sources, suggest them to be added.

**Comment by AllanWang** [comment]
As far as I know, having a server requires self hosting, which I will not be looking into. I also don't like emailed bug reports because the friction is way too low and people will send any report they see if it's prefilled. GitHub isn't bad since reports generally come with context, so I think no reporting tool is fine. It isn't relevant in most of the bugs anyways.

**Comment by IzzySoft** [comment]
Well, I definitely didn't want to force some bug reporter unto you. What's not there cannot raise a flag, so fine with me :laughing:

**Comment by AllanWang** [comment]
Tracking label is already removed so this is done. BugSnag removal will be done with the PR above
