### ISSUE TITLE
3.1.0 can't load some images at fullscreen

### ISSUE THREAD

**Issue by ghost** [AllanWang/Frost-for-Facebook#1823]
Not every images have this issue.

_ Open a post with an image
_ Touch on "show at fullscreen" (in Italian is Visualizza a schermo intero)
_ Page is blank with a warning icon in the top left corner
_ Touching it shows "error image format not supported"

For instance:

https://m.facebook.com/photo.php?fbid=264618172331664&id=100063504490982&set=a.130414269085389&source=48

![Screenshot_2021-09-27-10-07-08-12](https://user-images.githubusercontent.com/15078341/134873995-1b322590-dbc4-4525-bf2e-dadde902053b.jpg)

![Screenshot_2021-09-27-10-10-31-26](https://user-images.githubusercontent.com/15078341/134874050-8242706a-ccdc-415b-981d-2c8c0b611acf.jpg)

**Details (please provide at least the app version):**
 - App Version: 3.1.0 froid
 - Android: 10
Issue is not present in 3.0.0 fdroid

**Comment by tomas4** [comment]
I can confirm this bug affects me as well. Moreover, the image download from the blank full screen view also does not work, or downloads file "downloadfile.bin".

**Comment by AllanWang** [comment]
Facebook has known incompatibilities with one of their common formats, based on this library: https://github.com/davemorrissey/subsampling-scale-image-view

Don't have the exact reference, but unless there's an updated library out there, image exceptions will remain there.

If you want you can provide a log in case the error is different, but it's a common enough issue that I removed the report option in the error dialog.

**Comment by tomas4** [comment]
I downgraded to 2.4.7 and catched the same error as discussed, so what I wrote in previous message is wrong, the problem seems to be upstream as you said. Regards, Tomas B. Dne 29. 9. 2021 7:48 napsal uživatel Allan Wang ***@***.***>:
Facebook has known incompatibilities with one of their common formats, based on this library: https://github.com/davemorrissey/subsampling-scale-image-view
Don't have the exact reference, but unless there's an updated library out there, image exceptions will remain there.
If you want you can provide a log in case the error is different, but it's a common enough issue that I removed the report option in the error dialog.

**Comment by tomas4** [comment]
Oh, and the "previous message" I wrote about had not been sent, so nevermind. Tomas B. Dne 29. 9. 2021 7:48 napsal uživatel Allan Wang ***@***.***>:
Facebook has known incompatibilities with one of their common formats, based on this library: https://github.com/davemorrissey/subsampling-scale-image-view
Don't have the exact reference, but unless there's an updated library out there, image exceptions will remain there.
If you want you can provide a log in case the error is different, but it's a common enough issue that I removed the report option in the error dialog.

**Comment by ruralTom** [comment]
Same here. Had to go back to 3.0 to get it to work. So the last two releases have the issue.

**Comment by AllanWang** [comment]
It would be helpful to get a log, or a post with the image if it's public. You could even try downloading the photo from web and sending it here for testing.

It sounds like there are two problems in place here, since the other error is reproducible regardless of Frost version

**Comment by tomas4** [comment]
Hello, this https://m.facebook.com/photo.php?fbid=4548334868558315&id=100001455406723&set=a.901895309868974&source=48is public post with image giving the "image format not supported" Info and not showing fullscreen. But it is not rare, for me greater part of images (photos) I am trying to see fullscreen have this problem. This post is mine, but normaly I am viewing photos of colleagues photograohers in a group having this problem. Maybe, can it be connected with original image size? We usually share relatively large pictures, although I scale mine to 1-3 Mpix before sharing usually. Hope this helps with something. Regards, Tomas BrunclikDne 1. 10. 2021 20:32 napsal uživatel Allan Wang ***@***.***>:
It would be helpful to get a log, or a post with the image if it's public. You could even try downloading the photo from web and sending it here for testing.
It sounds like there are two problems in place here, since the other error is reproducible regardless of Frost version

**Comment by tomas4** [comment]
Tried also 3.0 and it works for me, while latest 2.x had the same problem. Weird. Note: Using fdroid to install, in case there is any difference in the builds.

**Comment by ruralTom** [comment]
@AllanWang I think this and the issue about not being able to download images could be related. 

Is it a .bin issue?

**Comment by poppypundit** [comment]
I have the same issue. My phone has no Google apps. Not sure if it's done thing to do with Web view?

**Comment by ruralTom** [comment]
@poppypundit It could be, but the prior release worked fine. So I don't know...

**Comment by AllanWang** [comment]
There's a lot of factors. Bunch of library updates, app targets sdk 31 (which is what broke a lot of changes recently), general android updates, android OS updates, webview updates, etc.

I haven't looked into this yet but it's probably reproducible
