### ISSUE TITLE
Notifications don't load

### ISSUE THREAD

**Issue by michaelnelsongithub** [AllanWang/Frost-for-Facebook#1828]
Notifications do not load with 3.1.1.

**Comment by AllanWang** [comment]
not reproducible and 0 additional info

**Comment by michaelnelsongithub** [comment]
What information do you need, it's my first bug report. Notifications do not load, the screen is blank and no numbers populate on the toolbar. This started with 3.1.1.


________________________________

**Comment by michaelnelsongithub** [comment]
With 3.0.0 notifications were slow to load and you often had to pull down to refresh to get it to load, now with 3.1.1 they do not load and no number to indicate new notifications.

**Comment by AllanWang** [comment]
There are a few types of bugs:

* App bugs - typically reproducible for all regions because it's not related to web contents. If I can reproduce it, no other content is needed
* Facebook bugs - bugs from Facebook's end
  * Sometimes they are one off and they fix themselves
  * Sometimes they are regional and are hard to replicate elsewhere

I can't reproduce this so there isn't much to help, even if it's reproducible on your end. You can however confirm that this is an issue in your web browser, or downgrade to 3.0.0 and try again. If consistently get different results in both versions, then you can let me know. You can also try restarting the app in the event that does anything.

**Comment by michaelnelsongithub** [comment]
Would you recommend clearing the cache, uninstalling and reinstalling? It's not on Facebook's end as I have a backup app that I sometimes use and it was fine.

**Comment by AllanWang** [comment]
There isn't really a reason why clearing the cache should affect it, but you can try. If you want you can also downgrade if it's reproducibly only on 3.1.1

**Comment by michaelnelsongithub** [comment]
Went back to 3.0.0, it was still slow as it was prior to not working with 3.1.1. I removed it entirely and reinstalled. It seems to be working now.
