### ISSUE TITLE
Expandable notifications for message thread

### ISSUE THREAD

**Issue by BlueDrink9** [AllanWang/Frost-for-Facebook#1846]
I often miss messages with Frost that I would have seen with Messenger. The reason for this is that if you receive two messages in a row from a person, Frost's notification only previews the second one. On Messenger, only the second is previewed initially, but expanding the notification with a two-finger swipe will show all the previous messages in that thread.

What this means is that if someone sends a message then immediately follows it up with a closing punctuation mark or correction, with Frost I don't know what the message was about and I would have to open the app to check - but I don't know if it is urgent enough to do that.

It would be marvellous to implement [expanded notifications](https://developer.android.com/training/notify-user/expanded) with the contents of previous messages, rather than replacing the existing notification with the most recent message contents.

**Comment by BlueDrink9** [comment]
Apologies, duplicate of #1731

**Comment by BlueDrink9** [comment]
Actually, I'm going to re-open this because I think it is a better description than the other issue. Feel free to close it as duplicate if you disagree.

I would open a PR for this, but I don't want to set up a whole android build environment just to test it. Looking at the [three](https://github.com/AllanWang/Frost-for-Facebook/blob/dev/app/src/main/kotlin/com/pitchedapps/frost/services/NotificationService.kt) [notification code](https://github.com/AllanWang/Frost-for-Facebook/blob/dev/app/src/main/kotlin/com/pitchedapps/frost/services/NotificationUtils.kt) [files](https://github.com/AllanWang/Frost-for-Facebook/blob/dev/app/src/main/kotlin/com/pitchedapps/frost/services/FrostNotifications.kt) it seems like it wouldn't be too much to implement.

https://github.com/AllanWang/Frost-for-Facebook/blob/6914873473951e2e129a8cd5906805f00d3b4068/app/src/main/kotlin/com/pitchedapps/frost/services/FrostNotifications.kt#L274-L280

At this point, we would modify it to

```kotlin
    val notifBuilder = context.frostNotification(channelId)
.setContentTitle(context.string(R.string.frost_name))
    .setContentText("$count ${context.string(fbItem.titleId)}")
    .setGroup(group)
    .setGroupSummary(true)
    .setContentIntent(pendingIntent)
    .setCategory(Notification.CATEGORY_SOCIAL)
.setStyle(NotificationCompat.BigTextStyle()
                  .bigText(messagesContent))
```

The hardest part, I think, would be keeping track of the content of the previous messages, rather than just displaying the count. That might require a more wide-reaching change. Maybe creating a new data structure for storing unread messages might be the best way to go.

**Comment by AllanWang** [comment]
The notification you see collapses all notifications from messages/a specific category, vs any specific thread in the category. Notification display changes aren't difficult, but fetching messages is.

There's no API used for getting notifications, and I simply parse the message page (basic only, not messenger). You only see a small preview there, and that's what you get. The frequency is also limited to at most once every 15 min. If someone sends you 3 messages, messenger can get that and append it, whereas Frost will only be able to get the last one at the time of fetching.

There is technically work that could be done if a user sends a message every 20 min over the course of an hour. I don't recall the behaviour for Frost as this is message specific, but that's not really what you're looking for here. This could raise additional concerns since it gives user the impression of message history, while the history itself cannot always be accurate. In a way this is an anti feature as it's misleading.

Will take opinions, but for now I think this is essentially infeasible until there's a way to get push notifications

**Comment by AllanWang** [comment]
Closing as I don't think it's feasible without losing accuracy. I did take a look at push notifications again (#1382), but it's still very finicky even in the official firefox browser for me
