### ISSUE TITLE
Notification defaults

### ISSUE THREAD

**Issue by gareins** [AllanWang/Frost-for-Facebook#1847]
I got my wife, a frequent facebook user, testing the app and her first comment was: why are there so many notifications?

I believe that Facebook mobile app only does sound notification rarely, when Frost probably does not parse what type a notification it is and if the notification should be loud or silent or even invisible on your phone. 

There is no perfect solution, but maybe a first boot menu choosing between "no notifications", "only notify for messages" and "all notifications" could be useful for users like her who will not go configuring settings, especially if she is just testing the app.

PS: do you find this type of feedback useful? I am expecting more comments from her and should I even post them?

**Comment by AllanWang** [comment]
I'm not too convinced that Frost sends out more notifications than web (at least the browser). The app itself may have configurations per channel, and my assumption is that Facebook configurations determine whether notifications are shown vs whether they produce sounds.

From a UX perspective, people will tend to want notifications, and have the opportunity to opt out of them if they find it annoying. This is usually better than hiding notifications and having them not realizing it, and if we end up showing configurations for every main setting, we my as well launch the settings page instead. 

There is indeed already an option to enabling general notifications and message notifications, for the active accounts or for all accounts. There's also a way to ignore certain keywords from notifying.

This type of feedback can be useful for you if it's a question (like this one), since I or someone else can answer it. Big feature requests are rarely useful in a sense since I'm maintaining Frost with limited time, but if there's a bug that's big enough, I could end up supporting it. I for instance don't use Messenger in Frost, but I added it with it broke for many users around the world.
