### ISSUE TITLE
Frost for Facebook

### ISSUE THREAD

**Issue by Moonshinebeam** [AllanWang/Frost-for-Facebook#1858]
Frost for Facebook (A fast and extensive third party wrapper for Facebook.)
https://f-droid.org/packages/com.pitchedapps.frost/

**Comment by Moonshinebeam** [comment]
Doesn't work well. However, and foremost for me, you worked for Google and nothing showed dates, licensing, etc...also this does not appear congruent with githubs reporting style...3 of the latter make me believe this may be used as Spyware? I see no comments or changed to 103 issues? Furthermore Frost, has absolutely no encryption as in implied by use of words foil or wrapper. It leaves everyone and I do mean anyone and everyone open to hacking. No safety nets what so ever???

**Comment by creativetrendsapps** [comment]
> Doesn't work well. However, and foremost for me, you worked for Google and nothing showed dates, licensing, etc...also this does not appear congruent with githubs reporting style...3 of the latter make me believe this may be used as Spyware? I see no comments or changed to 103 issues? Furthermore Frost, has absolutely no encryption as in implied by use of words foil or wrapper. It leaves everyone and I do mean anyone and everyone open to hacking. No safety nets what so ever???

Huh?

**Comment by AllanWang** [comment]
Since this is bumped

> You worked for Google

Still do, so what? Am I not allowed to contribute to open source software?

> nothing showed dates

What dates do I need to show?

> licensing

This project is licensed under GPL v3, as shown very early on in the project. It's both in a license file, standard to Github, and in every Kotlin source file header.

> does not appear congruent with githubs reporting style

Not sure what this means

> may be used as Spyware

You definitely can and should be skeptical of software that asks for your passwords. Facebook has a very limited api, so anyone who wishes to access the newsfeed cannot do so with that alone. I've mentioned this a few times across other posts on reddit and xda. Be _very_ careful with web wrappers.

> I see no comments or changes to 103 issues

I'm one person, I only maintain this now, so I naturally don't have a response to each issue. Again, this is a web wrapper, so many of the bugs aren't even reproducible consistently (per region, per user, per time, etc).

> has absolutely no encryption as in implied by use of words foil or wrapper

Where do I use the word foil? Wrapper means (not implies) that this project takes on a general custom browser, with some extra features added. It wraps their mobile site, which is what web wrapper means. 'Fast' and 'extensive' are subjective. Frost isn't fast compared to just using a normal browser without features, and it probably can't be. Frost may be faster than the native app depending on your needs (though if built properly without other services, it shouldn't be either)

> It leaves everyone and I do mean anyone and everyone open to hacking

I'm not aware of any more vulnerabilities than you using Facebook's mobile site in any other browser. If there is a problem, I'd be happy to hear it. Again, with all projects, use it at your own risk. Regardless of what I say, you can look at the code, build yourself, and raise issues like these ones if you have questions. It is not in my interest to offer a third party solution that has solvable vulnerabilities, even if 'you have the option not to use it'

> No safety nets what so ever

The only safety nets I state and think I can feasibly offer is creating an application that limits native app permissions and background services. What Facebook does on their own site, and what you choose to put on said site, is not in my control, nor in my interest to control.
